contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.sendmail , name="sendmail")
]

estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('contact/', include('contact.urls')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

agents/models.py
from django.db import models

# Create your models here.
class Agent(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    short_note = models.TextField(max_length=500)
    profile_img = models.ImageField(upload_to='photos/agents/%Y/%m/%d/', blank=True)
    facebook = models.URLField(max_length=200, blank=True, default="#")
    twitter = models.URLField(max_length=200, blank=True, default="#")
    linkedIn = models.URLField(max_length=200, blank=True, default="#")
    email = models.EmailField(max_length=254)
    is_mvp = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    

contact/models.py
from django.db import models

# Create your models here.

listings/models.py
from django.db import models
from datetime import datetime
from agents.models import Agent

# Create your models here.
class Listing(models.Model):

    CONTRACT_TYPE=(
        ('RENT','RENT'),
        ('SALE','SALE')
    )

    CITY = (
        ('Accra','Accra'),
        ('Kumasi','Kumasi'),
        ('Takoradi','Takoradi')
    )

    agent = models.ForeignKey(Agent, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50, choices=CITY, blank=False)
    description = models.TextField(max_length=500)
    property_type = models.CharField(max_length=500)
    reference = models.CharField(max_length=50)
    price = models.IntegerField()
    bathroom = models.IntegerField()
    room = models.IntegerField()
    bed = models.IntegerField()
    garage = models.IntegerField()
    garage_area = models.DecimalField(max_digits=4, decimal_places=1)
    home_area = models.DecimalField(max_digits=4, decimal_places=1)
    lot_area = models.DecimalField(max_digits=4, decimal_places=1)
    parking_lot = models.IntegerField()
    contract = models.CharField(max_length=10, choices=CONTRACT_TYPE, default='SALE')
    list_date = models.DateTimeField(default=datetime.now, blank=True)
    
    # images model
    main_image = models.ImageField(upload_to='photos/%Y/%m/%d/')
    feature_image_1 = models.ImageField(upload_to='photos/property/%Y/%m/%d/', blank=True, default="photos/default/default.jpg")
    feature_image_2 = models.ImageField(upload_to='photos/property/%Y/%m/%d/', blank=True, default="photos/default/default.jpg")

    """
    Other Property info
    """ 
    is_featured = models.BooleanField(default=False)
    is_top_property = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    

agents/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render,redirect
from django.core.mail import send_mail
import os

# Create your views here.
def sendmail(request):
    if request.method == "POST":
        prop_name = request.POST.get('property')
        agentmail = request.POST.get('agentmail').replace('/','')
        customer_name = request.POST.get('name')
        message = request.POST.get('message')
        property_id = request.POST.get('propertyid').replace('/','')
        customer_email = request.POST.get('email').replace('/','')

    send_mail(
        'New Property Listing',
        'You property ' + prop_name + ' has a new inquiry from '+ customer_name + ' & email' + customer_email + 'with the message '+ message,
        'hello@maxnimble.com',
        ['larteyelvis@outlook.com'],
        fail_silently=True
    )
    return redirect('/listings/'+property_id)

listings/views.py
from django.shortcuts import render
from .models import Listing
from agents.models import Agent
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    property = Listing.objects.order_by('-list_date').filter(is_published=True)
    agents = Agent.objects.all()
    paginator = Paginator(property,10)
    page = request.GET.get('page')
    paged_property = paginator.get_page(page)

    if request.method == "GET":
        context ={
            "prop": paged_property,
            "agents": agents,
        }
    
    return render(request, 'listings/listings.html', context)

def listing(request, listing_id):
    property = Listing.objects.get(pk=listing_id)
    agents = Agent.objects.all()
    if request.method == "GET":
        context={
            "property":property,
            "agents":agents
        }

    return render(request, 'listings/listing.html', context)

def search(request):
    return render(request, 'listings/search.html')

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from listings.models import Listing
from agents.models import Agent
from listings.choices import *


# Create your views here.
def index(request):
    property = Listing.objects.filter(is_published=True).filter(is_featured=True)
    top_property = Listing.objects.filter(is_published=True).filter(is_top_property=True)
    agents = Agent.objects.all()
    
    if request.method == "GET":
        context ={
            "prop": property,
            "topprop": top_property,
            "agents":agents,
            "contract": contract,
            "city": city,
            "bath": Bath,
            "bed": Bed,
            "price": Price
        }

        print(Listing.CITY)

    return render(request, 'pages/index.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="english">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Azenta Template">
    <meta name="keywords" content="Azenta, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Real Estate | MiCasa</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder --> 
    <!-- <<div id="preloder">
        <div class="loader"></div>
    </div> -->
        <!-- Offcanvas Menu Section Begin -->
        <div class="offcanvas-menu-overlay"></div>
        <div class="canvas-open">
            <i class="icon_menu"></i>
        </div>
        <div class="offcanvas-menu-wrapper">
            <div class="canvas-close">
                <i class="icon_close"></i>
            </div>
            <div class="language-bar">
                <div class="language-option">
                    <img src="{% static 'img/flag.png'%}" alt="">
                    <span>English</span>
                    <i class="fa fa-angle-down"></i>
                    <div class="flag-dropdown">
                        <ul>
                            <li><a href="#">English</a></li>
                            <li><a href="#">Germany</a></li>
                            <li><a href="#">China</a></li>
                        </ul>
                    </div>
                </div>
                <div class="property-btn">
                    <a href="{% url 'admin:index'%}" class="property-sub">Submit Property</a>
                </div>
            </div>
            <nav class="main-menu">
                <ul>
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'listings' %}">Property</a></li>
                </ul>
            </nav>
            <div class="nav-logo-right">
                <ul>
                    <li>
                        <i class="icon_phone"></i>
                        <div class="info-text">
                            <span>Phone:</span>
                            <p>(+233) 209 0999 42</p>
                        </div>
                    </li>
                    <li>
                        <i class="icon_map"></i>
                        <div class="info-text">
                            <span>Address:</span>
                            <p>Amasaman, <span>Accra-Ghana</span></p>
                        </div>
                    </li>
                    <li>
                        <i class="icon_mail"></i>
                        <div class="info-text">
                            <span>Email:</span>
                            <p>elvis@lartey.dev</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Offcanvas Menu Section End -->
    
        <!-- Header Section Begin -->
        <header class="header-section">
            <div class="top-nav">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7">
                            <nav class="main-menu">
                                <ul>
                                    <li class="active"><a href="{% url 'index'%}">Home</a></li>
                                    <li><a href="{% url 'listings'%}">Property</a></li>
                                </ul>
                            </nav>
                        </div>
                        <div class="col-lg-5">
                            <div class="top-right">
                                <div class="language-option">
                                    <img src="{% static 'img/flag.png'%}" alt="">
                                    <span>English</span>
                                    <i class="fa fa-angle-down"></i>
                                    <div class="flag-dropdown">
                                        <ul>
                                            <li><a href="#">English</a></li>
                                            <li><a href="#">Germany</a></li>
                                            <li><a href="#">China</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <a href="{% url 'admin:index'%}" class="property-sub">Submit Property</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nav-logo">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="logo">
                                <a href="{% url 'index'%}"><img src="{% static 'img/logo.png'%}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-lg-9">
                            <div class="nav-logo-right">
                                <ul>
                                    <li>
                                        <i class="icon_phone"></i>
                                        <div class="info-text">
                                            <span>Phone:</span>
                                            <p>(+233) 209 0999 42</p>
                                        </div>
                                    </li>
                                    <li>
                                        <i class="icon_map"></i>
                                        <div class="info-text">
                                            <span>Address:</span>
                                            <p>Amasaman, <span>Accra-Ghana</span></p>
                                        </div>
                                    </li>
                                    <li>
                                        <i class="icon_mail"></i>
                                        <div class="info-text">
                                            <span>Email:</span>
                                            <p>elvis@lartey.dev</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Header End -->

    {% block content %} {%endblock%}

 <!-- Partner Carousel Section Begin -->
 <div class="partner-section">
    <div class="container">
        <div class="partner-carousel owl-carousel">
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-1.png'%}" alt="">
                </div>
            </a>
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-2.png' %}" alt="">
                </div>
            </a>
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-3.png'%}" alt="">
                </div>
            </a>
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-4.png'%}" alt="">
                </div>
            </a>
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-5.png'%}" alt="">
                </div>
            </a>
        </div>
    </div>
</div>
<!-- Partner Carousel Section End -->

<!-- Footer Section Begin -->
<footer class="footer-section set-bg" data-setbg="{% static 'img/footer-bg.jpg'%}">
    <div class="container">
        <div class="footer-text">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer-logo">
                        <div class="logo">
                            <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                        </div>
                        <p>Subscribe our newsletter gor get notification about new updates.</p>
                        <form action="#" class="newslatter-form">
                            <input type="text" placeholder="Enter your email...">
                            <button type="submit"><i class="fa fa-location-arrow"></i></button>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1">
                    <!-- <div class="footer-widget">
                        <h4>Property City</h4>
                        <ul>
                            <li><i class="fa fa-caret-right"></i> <a href="#">Florida</a></li>
                            <li><i class="fa fa-caret-right"></i> <a href="#">New York</a></li>
                            <li><i class="fa fa-caret-right"></i> <a href="#">Washington</a></li>
                            <li><i class="fa fa-caret-right"></i> <a href="#">Los Angeles</a></li>
                        </ul>
                        <ul>
                            <li><i class="fa fa-caret-right"></i> <a href="#">St Louis</a></li>
                            <li><i class="fa fa-caret-right"></i> <a href="#">Jacksonville</a></li>
                            <li><i class="fa fa-caret-right"></i> <a href="#">San Jose</a></li>
                            <li><i class="fa fa-caret-right"></i> <a href="#">San Diego</a></li>
                        </ul>
                    </div> -->
                </div>
                <div class="col-lg-2">
                    <div class="footer-widget">
                        <h4>Social</h4>
                        <ul class="social">
                            <li><i class="ti-facebook"></i> <a href="#">Facebook</a></li>
                            <li><i class="ti-instagram"></i> <a href="#">Instagram</a></li>
                            <li><i class="ti-twitter-alt"></i> <a href="#">Twitter</a></li>
                            <li><i class="ti-google"></i> <a href="#">Google+</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="footer-widget">
                        <!-- <h4>Contact Us</h4>
                        <ul class="contact-option">
                            <li><i class="fa fa-map-marker"></i> 16 Creek Ave. Farming, NY</li>
                            <li><i class="fa fa-phone"></i> (+88) 666 121 4321</li>
                            <li><i class="fa fa-envelope"></i> info.colorlib@gmail.com</li>
                            <li><i class="fa fa-clock-o"></i> Mon - Sat, 08 AM - 06 PM</li>
                        </ul> -->
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-text">
            <p><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved 
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p></p>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js '%}"></script>
    <script src="{% static 'js/bootstrap.min.js '%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js '%}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js '%}"></script>
    <script src="{% static 'js/jquery.slicknav.js '%}"></script>
    <script src="{% static 'js/jquery-ui.min.js '%}"></script>
    <script src="{% static 'js/owl.carousel.min.js '%}"></script>
    <script src="{% static 'js/main.js '%}"></script>
</body>

</html>

templates/listings/listings.html
{% extends 'base.html'%}
{% load static %}
{% load humanize %}

{% block content %}
<!-- Map Section Begin -->
    <div class="map">
    <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2942.5524090066037!2d-71.10245469994108!3d42.47980730490846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e3748250c43a43%3A0xe1b9879a5e9b6657!2sWinter%20Street%20Public%20Parking%20Lot!5e0!3m2!1sen!2sbd!4v1577299251173!5m2!1sen!2sbd"
        height="500" style="border:0;" allowfullscreen=""></iframe>
    <div class="icon-list">
        <div class="icon icon-1">
            1
        </div>
        <div class="icon icon-2">
            2
        </div>
        <div class="icon icon-3">
            3
        </div>
        <div class="icon icon-4">
            4
        </div>
        <div class="icon icon-5">
            5
        </div>
    </div>
    </div>
<!-- Map Section End -->

<!-- Property Section Begin -->
    <section class="property-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="property-sidebar">
                        <h4>Search Property</h4>
                        <form action="#" class="sidebar-search">
                            <div class="sidebar-btn">
                                <div class="bt-item">
                                    <input type="radio" name="s-type" id="st-buy" checked>
                                    <label for="st-buy">Buy</label>
                                </div>
                                <div class="bt-item">
                                    <input type="radio" name="s-type" id="st-rent">
                                    <label for="st-rent">Rent</label>
                                </div>
                            </div>
                            <select>
                                <option value="">Locations</option>
                            </select>
                            <select>
                                <option value="">Status</option>
                            </select>
                            <select>
                                <option value="">No of Bedroom</option>
                            </select>
                            <select>
                                <option value="">No of Bathrooms</option>
                            </select>
                            <select>
                                <option value="">No of Guest</option>
                            </select>
                            <div class="room-size-range">
                                <div class="price-text">
                                    <label for="roomsizeRangeP">Size:</label>
                                    <input type="text" id="roomsizeRangeP" readonly>
                                </div>
                                <div id="roomsize-range-P" class="slider"></div>
                            </div>
                            <div class="price-range-wrap">
                                <div class="price-text">
                                    <label for="priceRangeP">Price:</label>
                                    <input type="text" id="priceRangeP" readonly>
                                </div>
                                <div id="price-range-P" class="slider"></div>
                            </div>
                            <button type="submit" class="search-btn">Search Property</button>
                        </form>
                        <div class="best-agents">
                            <h4>Best Agents</h4>
                            {% for agent in agents %}
                                <a href="#" class="ba-item">
                                    <div class="ba-pic">
                                        <img src="{{agent.profile_img.url}}" alt="" height="100px" width="80px">
                                    </div>
                                    <div class="ba-text">
                                        <h5>{{agent.name}}</h5>
                                        <span>{{agent.title}}</span>
                                        <p class="property-items">{{agent.listing_set.count}} property </p>
                                    </div>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <h4 class="property-title">Property</h4>
                    <div class="property-list">

                        {% if prop %}
                            {% for property in prop %}
                            <div class="single-property-item">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="property-pic">
                                         <a href="{%url 'listing' property.id%}"> <img src="{{property.main_image.url}}" alt=""> </a>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="property-text">
                                            <div class="s-text">For {{property.contract}}</div>
                                            <a href="{%url 'listing' property.id%}">
                                                <h5 class="r-title">{{property.title}}</h5></a>
                                            <div class="room-price">
                                                <span>Start From:</span>
                                                <h5>${{property.price | intcomma}}</h5>
                                            </div>
                                            <div class="properties-location"><i class="icon_pin"></i> {{property.address}} </div>
                                            <p>{{ property.description }}</p>
                                            <ul class="room-features">
                                                <li>
                                                    <i class="fa fa-arrows"></i>
                                                    <p>{{property.home_area}} sqft</p>
                                                </li>
                                                <li>
                                                    <i class="fa fa-bed"></i>
                                                    <p>{{property.bed}} Bed Room</p>
                                                </li>
                                                <li>
                                                    <i class="fa fa-bath"></i>
                                                    <p>{{property.bathroom}} Baths</p>
                                                </li>
                                                <li>
                                                    <i class="fa fa-car"></i>
                                                    <p>{{property.garage}} Garage</p>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        {% else %}
                            <div class="col-md-12">
                                <p>No properties Available.</p>
                            </div>
                    </div>
                    {% if prop.has_other_pages %}
                        <div class="property-pagination">
                            {% if prop.has_previous %}
                                <a class="page-link" href="?page={{property.previous_page_number}}">
                                    <<
                                </a>
                            {% else %}
                                <a class="page-link" ><<</a>
                            {% endif %}
                            {% for i in prop.paginator.page_range %}
                                {% if prop.number == i %}
                                    <a class="page-link" href="#">{{i}}</a>
                                {% endif %}
                            {% endfor %}
                            <a href="#">>></a>
                        </div>
                    {% endif%}
                    {% endif%}
                </div>
            </div>
        </div>
    </section>
<!-- Property Section End -->

{% endblock %}

templates/listings/search.html
<h1> Search Page</h1>